---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 2 * * *"

defaults:
  run:
    working-directory: 'nginx'

jobs:
  molecule:
    name: Molecule
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          path: 'nginx'

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.12'

#      - name: Clear Python cache directories
#        run: |
#          rm -rf /opt/hostedtoolcache/Python/3.10.12/x64
#          rm -rf ~/.cache/pip

      - name: Install test dependencies.
        run: |
          rm -rf ~/.cache/pip
          rm -rf ~/.cache/pip3
          pip3 install -r nginx/requirements.txt
          pip3 install ansible-core==2.16.8
          pip3 install --upgrade paramiko cryptography
          pyth3 on -m site &> /dev/null && PATH="$PATH:`python3 -m site --user-base`/bin"
          molecule --version
          ansible --version
          pip3 freeze

      - name: Run Molecule tests.
        run: |
          molecule destroy --all
          molecule converge
